--- #YAML:1.0
name:                DBIx-DWIW
version:             0.50
abstract:            Robust and simple DBI wrapper to Do What I Want (DWIW)
license:             ~
author:              
    - Jeremy Zawodny <Jeremy@Zawodny.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBD::mysql:                    2
    DBI:                           1.12
    Time::HiRes:                   0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
